# Generated by Django 5.0.9 on 2024-11-04 20:54

import MyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hod', models.CharField(max_length=250)),
                ('salary', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to=MyApp.models.Employee.nameFile)),
            ],
        ),
    ]
